# Docker Compose override for GhostAI DLP SDK
# This extends the base docker-compose.yml with the main application

version: '3.8'

services:
  ghostai-dlp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy-key-for-testing}
      - HF_TOKEN=${HF_TOKEN:-}
      - POSTGRES_USER=${POSTGRES_USER:-ghostai}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ghostai123}
      - POSTGRES_DB=${POSTGRES_DB:-ghostai}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    depends_on:
      - redis
      - db
    volumes:
      - ./src:/app/src:ro
      - ./demo_rag:/app/demo_rag:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import ghostai; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a development service with hot reload
  ghostai-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "5001:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy-key-for-testing}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./src:/app/src
      - ./demo_rag:/app/demo_rag
    command: ["python", "-m", "ghostai.proxy_api.proxy"]
    depends_on:
      - redis
      - db
    profiles:
      - dev
