"""baseline

Revision ID: 092a2a33efbe
Revises: 
Create Date: 2025-09-28 20:49:17.386245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '092a2a33efbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dlp_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('detector', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('avg_line_len', sa.Float(), nullable=True),
    sa.Column('max_line_len', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dlp_findings')
    # ### end Alembic commands ###
