profiles:
  runtime:
    presidio:
      enabled: true
      anonymize: true
    trufflehog:
      enabled: false
    gitleaks:
      enabled: false
    promptguard2:
      enabled: false
      threshold: 0.85
    regex_secrets:
      enabled: true

  # part dan will be working on
  ci:
    # add yelp secrets
    yelp:
      enabled: true
    presidio:
      enabled: false
      anonymize: false
    trufflehog:
      enabled: true
    gitleaks:
      enabled: true
    promptguard2:
      enabled: false
      threshold: 0.7
