profiles:
  runtime:
    presidio:
      enabled: true
      anonymize: true
    trufflehog:
      enabled: true
    gitleaks:
      enabled: true
    promptguard2:
      enabled: false
      threshold: 0.85
    bert_jailbreak:
      enabled: true
      threshold: 0.5
    regex_secrets:
      enabled: true
    image_exploit:
      enabled: true
      threshold: 0.8
    pdf_exploit:
      enabled: true
      threshold: 0.7

  # part dan will be working on
  ci:
    # add yelp secrets
    yelp:
      enabled: true
    presidio:
      enabled: false
      anonymize: false
    trufflehog:
      enabled: true
    gitleaks:
      enabled: true
    promptguard2:
      enabled: false
      threshold: 0.7
