profiles:
  runtime:
    presidio:
      enabled: true
      anonymize: true
    trufflehog:
      enabled: false
    gitleaks:
      enabled: false
    promptguard2:
      enabled: true
      threshold: 0.85

  ci:
    presidio:
      enabled: false
      anonymize: false
    trufflehog:
      enabled: true
    gitleaks:
      enabled: true
    promptguard2:
      enabled: false
      threshold: 0.7
